-- VISTAS INDEXADAS

USE ADVENTUREWORKS
GO

SET STATISTICS IO ON

SELECT ProductID,SUM(CASE WHEN TRANSACTIONTYPE='P' THEN
                     Quantity ELSE -Quantity END) AS STOCK
FROM
Production.TransactionHistory
GROUP BY ProductID

-- CREANDO UNA VISTA INDEXADA

CREATE VIEW DBO.STOCK
WITH SCHEMABINDING
AS

SELECT ProductID,SUM(CASE WHEN TRANSACTIONTYPE='P' THEN
                     Quantity ELSE -Quantity END) AS STOCK,
       COUNT_BIG(*) AS QTY 
FROM
Production.TransactionHistory
GROUP BY ProductID

GO

-- CREAMOS EL INDICE SOBRE LA VISTA

CREATE UNIQUE CLUSTERED INDEX I_STOCK ON
DBO.STOCK(ProductID)

-- HACEMOS EL SELECT 

SELECT * FROM DBO.STOCK

