USE ADVENTUREWORKS
GO

-- CREAMOS UN SINONIMO
CREATE SYNONYM EMPLEADOS FOR HUMANRESOURCES.EMPLOYEE
GO
-- PROBAMOS EL SINONIMO
  SELECT * FROM EMPLEADOS
-- BORRAMOS EL SINONIMO
DROP SYNONYM EMPLEADOS

--------------------------------------------------------------------------------------------
-- SEGURIDAD Y SONONIMOS
--------------------------------------------------------------------------------------------
 -- CREAMOS UN NUEVO LOGIN Y USUARIO

 CREATE LOGIN MADMAX WITH PASSWORD = 'PEPE'  
 GO

 CREATE USER MADMAX FOR LOGIN MADMAX WITH DEFAULT_SCHEMA=SALES

 -- CREAMOS UN NUEVO SINONIMO
 CREATE SYNONYM CLIENTES FOR SALES.CUSTOMER
 GO

 -- LE DAMOS PERMISO A MADMAX SOBRE EL SINONIMO
  GRANT SELECT,INSERT,UPDATE,DELETE ON CLIENTES TO MADMAX
 -- NOS CONECTAMOS COMO MADMAX
 EXECUTE AS LOGIN='MADMAX'
 -- PROBAMOS DE USAR EL SINONIMO QUE SE TIENE PERMISO
 SELECT * FROM CLIENTES
 -- NO TIENE ESE USURIO PERMISOS SOBRE EL OBJETO CUSTOMER
 SELECT * FROM SALES.CUSTOMER
 -- REVERTIMOS EL USUARIO
 REVERT

 -- LIMPIAMOS LO GENERADO

 DROP SYNONYM CLIENTES
 DROP USER MADMAX
 DROP LOGIN MADMAX