
-- CURSORES

CREATE DATABASE TESTPER
GO

USE TESTPER
GO

CREATE TABLE T1 (C1 INT PRIMARY KEY, C2 INT, C3 CHAR(8000))
GO

DECLARE @I INT
SELECT @I = 0
WHILE (@I < 6000)
 BEGIN
   INSERT INTO T1 VALUES (@I,@I + 1000,'HOLA')
   SET @I = @I + 1
 END
 
 -- UPDATE SIMPLE
 
 BEGIN TRAN
  UPDATE T1 SET C2 = 1000 + C2
 COMMIT TRAN
 
 -- UPDATE USANDO CURSORES
 
 DECLARE MYCURSOR CURSOR FOR 
   SELECT C2 FROM T1
   
 OPEN MYCURSOR
 GO
 
 BEGIN TRAN
 FETCH MYCURSOR
 WHILE (@@FETCH_STATUS = 0)
 BEGIN
  UPDATE T1 SET C2 = 1000 + C2 WHERE CURRENT OF MYCURSOR
  FETCH MYCURSOR
 END
 COMMIT TRAN
 
 
 -- VEMOS LOS TIEMPOS
 
 SELECT TOP 1000
   TOTAL_WORKER_TIME/EXECUTION_COUNT AS AVG_CPU_COST,
   EXECUTION_COUNT,
   (SELECT SUBSTRING(TEXT,STATEMENT_START_OFFSET/2 + 1,
    (CASE WHEN STATEMENT_END_OFFSET = -1 THEN
     LEN (CONVERT(NVARCHAR(MAX),TEXT)) * 2
     ELSE STATEMENT_END_OFFSET END - statement_start_offset) /2)
     
     FROM sys.dm_exec_sql_text(SQL_HANDLE))  AS QUERY_TEXT
     FROM sys.dm_exec_query_stats 
     ORDER BY [AVG_CPU_COST] DESC
   
 