/*IMPLEMENTADO BASE DE DATOS*/
--CREANDO BASE DE DATOS
CREATE DATABASE PRUEBA
--ELIMINANDO BASE DE DATOS
DROP DATABASE PRUEBA
--IMPLEMENTANDO BASE DE DATOS RESERVA
--VERIFICAR QUE LA BASE DE DATOS NO ESTE CREADA
IF DB_ID('PRUEBA') IS NOT NULL
BEGIN
	USE MASTER
	DROP DATABASE PRUEBA
END
--CREAR BASE DE DATOS EN BLANCO
CREATE DATABASE PRUEBA
ON PRIMARY(
	NAME = 'PRUEBA_MDF',
	FILENAME = 'D:\DBRESERVA\PRUEBA.MDF',
	SIZE = 15MB,
	MAXSIZE =250MB,
	FILEGROWTH=10MB

),(
	NAME = 'PRUEBA_NDF',
	FILENAME = 'D:\DBRESERVA\PRUEBA.NDF',
	SIZE = 15MB,
	MAXSIZE = UNLIMITED,
	FILEGROWTH=10MB
)
LOG ON(
	NAME = 'PRUEBA_LDF',
	FILENAME = 'D:\DBRESERVA\PRUEBA.LDF',
	SIZE = 15MB,
	MAXSIZE =500MB,
	FILEGROWTH=10%
)

GO
--ACTIVAR BASE DE DATOS
USE PRUEBA
